# Generated by Django 5.2.18 on 2026-10-09 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(db_index=True)),
                ('response_time_ms', models.FloatField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'system_metrics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
