# Generated by Django 5.2.18 on 2026-10-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlog',
            name='actor_role',
            field=models.CharField(blank=True, default='ADMIN', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPPORT', 'Support'), ('READ_ONLY', 'Read-Only'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('CARD_ADD', 'Card Added'), ('CARD_DELETE', 'Card Deleted'), ('CARD_BLOCK', 'Card Blocked'), ('CARD_UNBLOCK', 'Card Unblocked'), ('CREDIT_LIMIT_UPDATE', 'Credit Limit Updated'), ('ROLE_CHANGE', 'User Role Changed'), ('FRAUD_FLAG', 'Fraud Flagged'), ('FRAUD_RESOLVE', 'Fraud Resolved'), ('PAYMENT', 'Payment Made'), ('ADMIN_VIEW', 'Admin Viewed Data'), ('EXPORT', 'Data Exported'), ('SYSTEM_CONFIG', 'System Config Changed')], max_length=50),
        ),
    ]
