services:
  db:
    build: ./db
    container_name: credit_card_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 25

  django:
    build: ./backend_django
    container_name: credit_card_django
    restart: always
    command: bash -c "python manage.py migrate --fake-initial && python manage.py runserver 0.0.0.0:8000"
    env_file: .env
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./backend_django:/app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  fastapi:
    build: ./backend_fastapi
    container_name: credit_card_fastapi
    restart: always
    command: python -m uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8001
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"

  frontend:
    build: ./frontend
    container_name: credit_card_frontend
    ports:
      - "3000:80"
    depends_on:
      - django
      - fastapi

volumes:
  db_data:
