# Generated by Django 5.2.17 on 2026-10-03 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=255)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('masked_card_number', models.CharField(max_length=20)),
                ('card_type', models.CharField(choices=[('CREDIT', 'Credit Card'), ('DEBIT', 'Debit Card')], default='CREDIT', max_length=10)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
