# Generated by Django 5.2.18 on 2026-10-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='card',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
