# Generated by Django 5.2.18 on 2026-10-09 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_credit_limit_card_is_blocked'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('SHOPPING', 'Shopping'), ('DINING', 'Dining & Food'), ('TRAVEL', 'Travel & Transport'), ('GROCERIES', 'Groceries & Supermarket'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Bills & Utilities'), ('HEALTHCARE', 'Healthcare & Pharmacy'), ('EDUCATION', 'Education'), ('OTHER', 'General / Other')], db_index=True, default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_info',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_reason',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_status',
            field=models.CharField(choices=[('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('FLAGGED', 'Flagged for Review'), ('BLOCKED', 'Blocked')], db_index=True, default='CLEAN', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_triggered', models.CharField(max_length=100)),
                ('risk_score', models.IntegerField(default=50)),
                ('details', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('CONFIRMED_FRAUD', 'Confirmed Fraud'), ('DISMISSED', 'Dismissed / False Positive')], default='PENDING_REVIEW', max_length=30)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_logs', to='cards.card')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_logs', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fraud Log',
                'verbose_name_plural': 'Fraud Logs',
                'db_table': 'fraud_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
